services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/srv/web
    ports:
      - "80:8000"
    env_file:
      - ./web/.env.dev
    depends_on:
      - db
    expose:
      - 80
  db:
    image: postgres:17.2-bookworm
    volumes:
      - ~/docker_data/singlebox/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=singlebox_user
      - POSTGRES_PASSWORD=singlebox_password
      - POSTGRES_DB=singlebox
